apiVersion: v1
kind: Service
metadata:
  name: envoyadmin-web-service
  namespace: faa-win
spec:
  selector:
    app: envoy-web
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port:  9901
    targetPort: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: envoyadmin-api-service
  namespace: faa-win
spec:
  selector:
    app: envoy-api
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port:  9901
    targetPort: 9901
