apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc-service
  namespace: faa-win
spec:
        #clusterIP: None
  selector:
    app: eshopwebmvc
  ports:
  - name: https
    protocol: TCP
    port: 9443 
    targetPort: 9443

