apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi-service
  namespace: faa-win
spec:
        #clusterIP: None
  selector:
    app: eshoppublicapi
  ports:
  - name: https
    protocol: TCP
    port:  9445 
    targetPort: 9445
