apiVersion: v1
kind: Service
metadata:
  name: eshopenvoy-service
  namespace: faa-win
spec:
  selector:
    app: eshoppublicapi
  ports:
  - name: https
    protocol: TCP
    port:  9901 
    targetPort: 9901
