kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-https
  namespace: faa-win
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
